### ISSUE TITLE
How to setup the plugin?

### ISSUE THREAD

**Issue by GulinSS** [intellij-purescript/intellij-purescript#158]
I've tried to open intellij-purescript.github.io but got 404. I've installed the plugin and added purescript language server to node_modules. Well, it didn't help me. The plugin only does syntax highlighting, nothing more. What should I do else to make it work completely?

**Comment by objarni** [comment]
@GulinSS the language server stuff is not very well functioning afaic. I'm running on Ubuntu, and it basically didn't work at all some weeks ago. @Neppord is there some documentation on what to expect w.r.t language server?

What I know should work cross platform:

- syntax highlighting
- navigate locally (within file) between variables/definitions and types

**Comment by Neppord** [comment]
@objarni there is a description in the marketplace that covers what should work as a minimum, since its not always updated.

**Comment by Neppord** [comment]
This issue was solved over a slack thread, the problem was that the `.spago` directory was excluded, so the plugin did not look in it to find references and documentation.
