### ISSUE TITLE
Symbol | disables comment highlighting

### ISSUE THREAD

**Issue by GulinSS** [intellij-purescript/intellij-purescript#191]
The usage of `|` disables comment highlighting:

![image](https://user-images.githubusercontent.com/1963644/113710808-d8e0ee00-96ec-11eb-81e1-2944bc56cfcd.png)
![image](https://user-images.githubusercontent.com/1963644/113710826-dd0d0b80-96ec-11eb-8baf-46b81749f53d.png)

**Comment by Neppord** [comment]
The reason why `|` "removes" color is because it becomes a doc comment, which has a different color then normal comments.

It however should be green and not "colorless".

Is it ok that i close this issue, or should we reword it?
