### ISSUE TITLE
Doesn't support 0.14 version

### ISSUE THREAD

**Issue by xgrommx** [intellij-purescript/intellij-purescript#264]
Hello, I try to use this plugin with version of purescript 0.14 but I got errors

![image](https://user-images.githubusercontent.com/1499594/122385757-d9f88c00-cf75-11eb-9066-9ef4a960e096.png)

How can I fix it? Or this plugin don't ready to use now?

**Comment by Neppord** [comment]
Sorry from your description it's not clear to me what that is broken.

The plugin is targeting the newest version of purescript untill it is stable, and then we will maybe try to handle more then one version.

**Comment by simonolander** [comment]
@xgrommx 
What are the errors that you got?

**Comment by Neppord** [comment]
I'm closing this one because of lack of response from the submitter.
