### ISSUE TITLE
Comment between where and import causes mis-parsing sometimes

### ISSUE THREAD

**Issue by Idran** [intellij-purescript/intellij-purescript#274]
Just noticed this while I was doing some coding. The code I was working on had its export lists followed by a where on the same line as the closing paren, a blank line, a comment, and the first import.  Essentially, this:

```
  ) where

-- TODO: comment
import Prelude
```

This seemed to cause the Purescript plugin to throw an incorrect "unexpected module prefix" error on the final expression in a do block within the first function declaration in the file.

When I change anything before the comment or remove the comment, the error disappears.  Then, any changes made to the code below the comment will cause it to reappear.

This code does compile and function properly, so I know it's an issue with the parser. In this particular code, it's also throwing "cannot resolve symbol" errors for basically everything being imported for reasons I haven't pinned down, which may be related/the root issue. None of these errors appear or disappear, though.

**Comment by Neppord** [comment]
Thanks for finding this.

Would you like to pair on fixing this issue? We are currently pair over at the hrrps://purescript.org/chat discord server, and organize sessions in the editors channel.

The parser code is quite bulky and the part of the code that is most like legacy so two people will definitely help.

**Comment by Neppord** [comment]
Could not reproduce, and no answer from OP.
