### ISSUE TITLE
Cannot support optional names for instances of type classes

### ISSUE THREAD

**Issue by xgrommx** [intellij-purescript/intellij-purescript#280]
Hello, now purescript has ability for optional names for instances of type classes. For example

```
class A a where
  someMethod :: a
```

Now this syntax is valid

```
instance A String where
  someMethod = identity
```

The same as

```
instance aString :: A String where
  someMethod = identity
```

But now in idea it doesn't work

![image](https://user-images.githubusercontent.com/1499594/134671271-ee2ebb8d-3853-4d33-b508-8f0279acc46f.png)

сс @Neppord

**Comment by Neppord** [comment]
I think this is where the change needs to happen (in `PureParsecParser.kt`) 
![image](https://user-images.githubusercontent.com/72190/134801032-df987a08-e888-4100-b529-a731f4a61a01.png)

**Comment by Neppord** [comment]
this was the change in purescript https://github.com/purescript/purescript/pull/4085

**Comment by Neppord** [comment]
this is the corresponding change we need to make:
![image](https://user-images.githubusercontent.com/72190/134801089-6f4daeb9-b4b3-4d95-88eb-d4dda12902f6.png)

**Comment by Neppord** [comment]
@xgrommx would you like to pair on this with me?

**Comment by xgrommx** [comment]
@Neppord how can I help you?
