### ISSUE TITLE
In-place evaluation as in haskell plugin for vscode

### ISSUE THREAD

**Issue by xgrommx** [intellij-purescript/intellij-purescript#286]
Hello @Neppord in haskell plugin for vscode exists in-place evaluation
https://github.com/haskell/haskell-language-server/blob/master/plugins/hls-eval-plugin/README.md
will be possible to create smth similar to in idea? as I know idea has evaluation window or smth similar

**Comment by Neppord** [comment]
Sounds like a lot of work, but there is nothing that sais it would not be possible.

You can start by taking a look on how it integrates with the LSP server, you should be able to do something similar. Probably build the feature first in the LSP server and then query it for the information to be displayed.

PR is welcome.

**Comment by Neppord** [comment]
Closing since no interest from reporter to make a PR, of a feature request.
