### ISSUE TITLE
Autocompletion doesn't match "do"

### ISSUE THREAD

**Issue by jbrains** [intellij-purescript/intellij-purescript#288]
I have a function in scope that happens to have the characters "do" in the middle of it. Whenever I type `do`, autocompletion matches this function name instead of `do`. This forces me to type `do<space>` in order to use do-notation.

**Comment by Neppord** [comment]
I'll take a look at this one. It might be that its due to the LSP server and not this plugin...

Would you never want it to autocomplete a function with the same name as a keyword?

**Comment by Neppord** [comment]
This is definitely the plugin, and not the LSP.

I think the solution is just to add all valid keywords to the autocomplete list and it should work.

**Comment by jbrains** [comment]
> Would you never want it to autocomplete a function with the same name as a keyword?

This is interesting. I'm not sure which is a better experience, when I type `do`:

- Match nothing.
- Match functions, but put the keyword "do" at the top of the list.
- Match functions, but only when I explicitly ask for autocompletion. (Don't autosuggest the functions to me.)

I can imagine wanting to name a function `doThis` and that I would want to match it if I typed `do<Ctrl+space>`, but I would consider it a distraction to match `doThis` when I only type `do`.

The _problem_ right now is that when I type `do<ENTER>`, this autosuggests _and_ autocompletes to the coincidentally-matching function name. I'd certainly like that to stop.

**Comment by Neppord** [comment]
@jbrains This should be solved now in the version available in the marketplace.

I made it so that it does the same as intellij does in java etc. Put keywords at the top of the completion list.

It could also be a good idea to create a live template for `do`, since most of the time you do have a new line etc. but im not sure if it is as useful as it would be for a `ado`.
