### ISSUE TITLE
Jump to symbol doesn't work for type aliases if symbol is referenced through module alias

### ISSUE THREAD

**Issue by rpolley** [intellij-purescript/intellij-purescript#294]
If for example we have module Foo:
```
module Foo where (
  Bar
)
type Bar = Int
```
and module Baz:
```
import Foo as Qux
type MyType = Qux.Bar
```
Then using goto symbol on Quix.Bar will not jump to the definition of it in module Foo.

**Comment by Neppord** [comment]
What would you expect instead should happen?

To me this sounds logical, that you go to the original definition.

**Comment by Neppord** [comment]
This sounds like it could be simple to fix.

If i understood what you meant, I didn't at first.

**Comment by rpolley** [comment]
Not sure if it's an "Error" but I just get the standard "Cannot find declaration to go to" message Intellij gives when it can't find where a symbol is defined.

**Comment by rpolley** [comment]
Also it looks like this is happening for anything typelevel, (i.e. newtypes and data declarations too, not just type aliases)
