### ISSUE TITLE
Jump to symbol doesn't work correctly for types imported via module aliases if there is a type definition with the same name in the module you're in

### ISSUE THREAD

**Issue by rpolley** [intellij-purescript/intellij-purescript#296]
minimal example:
a.purs:
```
module Foo where
type Bar = Int
```
b.purs
```
module Baz where
import Foo as Foo
type Bar = Foo.Bar
```
using go to symbol on 
```
type Bar = Foo.Bar
                          ^
```
jumps to
```
type Bar = Foo.Bar
       ^
```
rather than
```
type Bar = Int
       ^
```
(If you're curious the "real world example" here is something closer to 

```
import Halogen as H
type HalogenM m = H.HalogenM MyStateType MyActionType MySlotsType MyOutputType m
```

or

```
module Baz
import Foo as Foo
import Bar as Bar

type Config = 
{  foo :: Foo.Config
 , bar :: Bar.Config
}
```

)

**Comment by rpolley** [comment]
Should be the latest version, I updated to the latest Intellij picks up this morning. (Go to symbol usually works fine (thanks for fixing that btw), it's just that when there's a type with the same name that there's a problem, i.e. 
a.purs:
```
module Foo where
type Bar = Int
```
b.purs
```
module Baz where
import Foo as Foo
type FooBar = Foo.Bar
```
has no issues)

**Comment by Neppord** [comment]
Cool! Then this hopefully is a easy thing to fix as well.

Would you like to fix it together with me?
