### ISSUE TITLE
Single quote as character literal (''') not parsed correctly

### ISSUE THREAD

**Issue by jhilyar** [intellij-purescript/intellij-purescript#304]
Since Purescript strictly uses single quotes for character literals and double quotes for strings, ''' is proper Purescript syntax for a single quote as a character literal, but the plugin's parser doesn't seem to handle it correctly. When used, the plugin returns "Unexpected error. Expecting layout separator or layout end" for it, and basically explodes for the rest of the file.

**Comment by Neppord** [comment]
Thank you for reporting this.

I have not had time to respond, and haven't yet had time to research how hard this is to fix. The Lexer and Parser are handwritten and the most legacy part of the system. Sometimes it's easy and sometimes it very difficult to fix things like this.

Ill see if i can put in sometime this weekend.

Are you interested in fixing this with me?

**Comment by jhilyar** [comment]
Eventually I'd like to start helping with this plugin, as much as I use it, but unfortunately I don't have the bandwidth for that right now.

**Comment by Neppord** [comment]
it might be that you only need to replace the  `[^']` something that matches anything like `.`?

https://github.com/intellij-purescript/intellij-purescript/blob/5ad5e4b414e111cc13b886c2a2345b8cc02eec70/lexer/src/main/grammar/Purescript.flex#L160
