### ISSUE TITLE
Cannot run program "/bin/bash", No such file or directory

### ISSUE THREAD

**Issue by nhyne** [intellij-purescript/intellij-purescript#306]
I'm having problems running the plugin due to not having bash installed at that specific path. 

I think changing [this line](https://github.com/intellij-purescript/intellij-purescript/blob/41a679a298e202bbbd8ebff53c21f837b3144b9d/src/main/kotlin/org/purescript/ide/purs/Purs.kt#L12) to "/usr/bin/env bash ...." would solve the problem for me without breaking it for other users.

I was wondering if the team would be open to me submitting a PR for that change?

**Comment by Neppord** [comment]
More then happy, if you do :)!
