### ISSUE TITLE
Add import action on qualified things should import as qualified

### ISSUE THREAD

**Issue by i-am-the-slime** [intellij-purescript/intellij-purescript#315]
Right now when I type:

```
JSON.writeJSON
``` 

and then run an `import` action on `writeJSON` I get the following:

```
import Yoga.JSON (writeJSON)
```
In my import section.

However, I should be getting

```
import Yoga.JSON as JSON
```

Or potentially:

```
import Yoga.JSON (writeJSON) as JSON
```

Or ideally I get the choice.

**Comment by Neppord** [comment]
Interesting, this is close to one of my issues, which is that we always import from the module that declares the thing, and not from the "shortest" path that exports it.

**Comment by i-am-the-slime** [comment]
Not sure the shortest path is always the desired path. I think having the choice, but *ordering* by shortest path would be ideal.

**Comment by i-am-the-slime** [comment]
💥

**Comment by i-am-the-slime** [comment]
It is really cool, however I'd prefer if it was the open import instead, so:

```
import Yoga.JSON as JSON
```

instead of 

```
import Yoga.JSON (writeJSON) as JSON
```

If I did get autocomplete on `JSON.` I might reconsider 😁 .

**Comment by Neppord** [comment]
Why not both!? :)

Would you be kind to open a new issue for auto importing open imports?

**Comment by Neppord** [comment]
Ill create it
