### ISSUE TITLE
Dependencies in monorepos don't get resolved

### ISSUE THREAD

**Issue by i-am-the-slime** [intellij-purescript/intellij-purescript#332]
In spago you can [add relative dependencies to a project](https://github.com/purescript/spago#monorepo).

The plugin does not find those, however (they are red instead 😁 ).

Any idea how to get this to work without having to parse `dhall`?

**Comment by Neppord** [comment]
You could add the source to the project, that would probably work.

**Comment by i-am-the-slime** [comment]
Intellij has this in some workspace settings afterwards, I guess, right? I think it's actually cool enough then!

**Comment by Neppord** [comment]
It's a workaround for sure, let's see if we can implement the external library feature at some point

**Comment by Neppord** [comment]
https://plugins.jetbrains.com/docs/intellij/library.html

The documentation don't look to hard

**Comment by Neppord** [comment]
Also posible start to look for implementation com.intellij.util.indexing.IndexableSetContributor
