### ISSUE TITLE
Path cannot be null when running tests from IDEA

### ISSUE THREAD

**Issue by objarni** [intellij-purescript/intellij-purescript#348]
Tried using the new feature of hitting the play button in a test main file. Got this:

![image](https://user-images.githubusercontent.com/68198/221390879-76193418-72b1-4b43-a2ce-4a6d94de09c4.png)

**Comment by Neppord** [comment]
This should be fixed in version 0.73.12, thanks for Noticing!

**Comment by Neppord** [comment]
here is a link to the version if you want to download and try before it hits the marketplace https://plugins.jetbrains.com/plugin/9738-purescript/versions/stable/298742

**Comment by Neppord** [comment]
This might be fixed, re open if problem re appear
