### ISSUE TITLE
Rename refactoring does not rename type annotation

### ISSUE THREAD

**Issue by i-am-the-slime** [intellij-purescript/intellij-purescript#350]
Edit: I was lying about this, it actually renames the annotation when one is done. Might still be less confusing if it did it live.

Original: It would be nice if the rename refactoring also renamed the corresponding type signature.

<img width="460" alt="Bildschirm­foto 2023-03-05 um 17 11 35" src="https://user-images.githubusercontent.com/1588055/222972154-d3eab8c2-7474-42fd-a061-e944c9754ad2.png">

In a similar vein, it would be nice if one could start the refactoring on the definition.

**Comment by Neppord** [comment]
It doese, its just the preview that doesen't work

**Comment by i-am-the-slime** [comment]
Also this bit?

> In a similar vein, it would be nice if one could start the refactoring on the definition.

**Comment by Neppord** [comment]
Sorry was just going by the subject line.

However your second ask should also be fixed in newest version.

Den mån 6 mars 2023 11:05Mark Eibes ***@***.***> skrev:
