### ISSUE TITLE
Unnecessary parentheses inspection misidentifies necessary parens for accessing record properties in place

### ISSUE THREAD

**Issue by jhilyar** [intellij-purescript/intellij-purescript#351]
When a variable is a newtype of a record - for example, newtype Foo = Foo UnwrappedFoo, type UnwrappedFoo = { bar :: String } - the in-place pattern of (unwrap foo).bar to access the value of bar within the newtype variable is getting misidentified as unnecessary parentheses by the new inspection.

**Comment by jhilyar** [comment]
It looks like this also happens when the output of a function is a record, and there's a pattern like (f foo).bar to access the bar property of the output of f.

**Comment by Neppord** [comment]
Thank you this is gold! Ill fix it tomorrow!

**Comment by Neppord** [comment]
https://plugins.jetbrains.com/plugin/9738-purescript/versions/stable/305786 <- version that its fixed in
