### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by drathier** [intellij-purescript/intellij-purescript#353]
This gives a `malformed declaration` error:
```
thingy =
  VexceptT.ado
    (_ :: ThingId) <- f (getId thing) cred (thingData 3.0)
    in unit
```
plugin version `intellij-purescript v0.76.15`

**Comment by i-am-the-slime** [comment]
Woah, qualified ado?

**Comment by Neppord** [comment]
[v0.76.16](https://github.com/intellij-purescript/intellij-purescript/releases/tag/v0.76.16) fixes this issue
