### ISSUE TITLE
Autocomplete does not consider re-exported symbols

### ISSUE THREAD

**Issue by rpolley** [intellij-purescript/intellij-purescript#389]
Consider the editor state in the following screenshot:
![Screenshot from 2023-11-09 12-43-03](https://github.com/intellij-purescript/intellij-purescript/assets/23124989/1c6047e6-69ec-4c7d-95b6-8394986223a4)
The top completion here will add `import Data.Map.Internal (lookup) as Map`, which causes an `ImplicitQualifiedImport` warning on compile. (As an aside, it would be nice to be able to make autocompletion not consider modules like `Data.Map.Internal`, which are not meant to be imported from directly.

**Comment by Neppord** [comment]
So the bug is that a import is added even though the Member is already imported by existing imports?
