### ISSUE TITLE
Optimize imports removes used import of operator

### ISSUE THREAD

**Issue by i-am-the-slime** [intellij-purescript/intellij-purescript#391]
```
import Data.Options ((:=))
x = shallow := true
```

<img width="247" alt="image" src="https://github.com/intellij-purescript/intellij-purescript/assets/1588055/73a99e80-c956-48ac-ac2a-3a7efa65198d">

**Comment by Neppord** [comment]
Cant reproduce, need more context.

**Comment by Neppord** [comment]
Fixed by, fixing operator references that where broken, thank you @i-am-the-slime for fixing this together with me!
