### ISSUE TITLE
not working with spago@next

### ISSUE THREAD

**Issue by mendrik** [intellij-purescript/intellij-purescript#398]
Not sure if I do something wrong but the spago run configs still expect dhall. and my Main.purs has errors:

![image](https://github.com/intellij-purescript/intellij-purescript/assets/160805/2b1a0070-d8f8-479b-8a36-7fe64726c956)

**Comment by Neppord** [comment]
If you manually run Spago build, after removing the output directory, dose that work?

**Comment by mendrik** [comment]
build works, but it just doesn't pick up any of the import libs 🤔

**Comment by mendrik** [comment]
![image](https://github.com/intellij-purescript/intellij-purescript/assets/160805/77b55331-47ee-4d85-aebb-95a89ab4ca29)

![image](https://github.com/intellij-purescript/intellij-purescript/assets/160805/b870caab-2214-4487-aff1-7550556d3122)

I'm very new to spago/purs, so not sure if these screenshots help

**Comment by Neppord** [comment]
That "P" folder looks suss, is that how it should be or is it a bug in Spago, can't remember that the folder with modules was called "P"
