### ISSUE TITLE
False errors on qualified tag matching

### ISSUE THREAD

**Issue by chekoopa** [intellij-purescript/intellij-purescript#4]
Sometimes we need to match types from qualified imports. And some cases give false positives. Like this:

```purescript
update :: TS.Step -> Array TS.Step -> Update Model Msg
update current history m msg = case msg of
  NoOp -> m :> []
  Switch f -> (m {follow = f}) :> [ pure Bump ]
  Bump ->
    let
--    V  it swears from here    
      (TS.Step step) = case m.follow of 
        Current -> current
        History i -> fromMaybe TS.dummyStep $ history !! i
    in ( m { step = step } ) :> []
  _ -> m :> []
```

**Comment by Neppord** [comment]
hello @chekoopa as you can see there have not been a lot of development on this plug in for a while.

I plan to change that, but I don't know if this is stilla bug, and not how to priorities it.

You are welcome to join our mob/ensambe sessions if you want to have this fixed.

Until then I'll close this issue and hope you or someone else can report it when the project is a bit more stable.
