### ISSUE TITLE
Name scoping error in pattern match lambda

### ISSUE THREAD

**Issue by drathier** [intellij-purescript/intellij-purescript#402]
`\{ a, b: ob, c } ->` seemingly introduces `b` into scope, when only `a`, `ob` and `b` should be introduced. In my case, `b` shadowed an outer let-bound variable also called `b`, so intellij-haskell though that outer let-bound value was unused.

This should be a small example, and it seems to reproduce the same issue:
```
f =
  let b = 42
  in \{ a, b: ob, c } -> b
```

**Comment by Neppord** [comment]
Did you mean purescript instead of haskell?

**Comment by drathier** [comment]
Yes, I meant purescript. Edited :)
