### ISSUE TITLE
Fails to parse a function called `as`

### ISSUE THREAD

**Issue by i-am-the-slime** [intellij-purescript/intellij-purescript#406]
It seems to not like `as` because that's a keyword but the compiler is okay with it.

```purs
module Repro
  ( as
  ) where

import Prelude

import Data.Symbol (class IsSymbol)
import Data.Variant (Variant, inj)
import Prim.Row (class Cons)
import Type.Proxy (Proxy(..))

as
  ∷ ∀ @sym a r1 r2
  . Cons sym a r1 r2
  ⇒ IsSymbol sym
  ⇒ a
  → Variant r2
as = inj (Proxy :: Proxy sym)

```

**Comment by Neppord** [comment]
This should be easy, just add "as" token to the list of tokens that are allowed as identifiera in the parser.

**Comment by i-am-the-slime** [comment]
Just had a look, at it seems like `as` is already there:

https://github.com/intellij-purescript/intellij-purescript/blob/8c692df8d6a5607755dddfcf3648f0885608d482/src/main/kotlin/org/purescript/parser/ParserDefinitions.kt#L27

**Comment by Neppord** [comment]
Then its in the layout lexer check that "as" also in the same case as identifiera...

**Comment by i-am-the-slime** [comment]
I am so sorry!

I wasn't checking properly when making the issue smaller. As was syntax-highlighted wrong, but it still works.
It was a type annotation from the language server that caused a problem:

```purs
at ∷ ∀ (@name ∷ Symbol) (r1 ∷ Row Type) (r2 ∷ Row Type) (r ∷ Row Type) (a ∷ Type) (b ∷ Type). IsSymbol name ⇒ Cons name a r r1 ⇒ Cons name b r r2 ⇒ (∀ (p ∷ Type -> Type -> Type). Strong p ⇒ p a b → p (Record r1) (Record r2))
```

The `(@name :: Symbol)` part is the problem.
