### ISSUE TITLE
Implement quick documentation

### ISSUE THREAD

**Issue by Neppord** [intellij-purescript/intellij-purescript#71]
It would be nice if the plugin could use the already built documentation help in the purs ide command some how

**Comment by Neppord** [comment]
It doesn't seam to be able to use the LSP for documentation. Maybe @kritzcreek knows if the purs ide feature has documentation support?

**Comment by simonolander** [comment]
I'm investigating what it looks like if the lexer differentiates between line and doc comments. If we then tie the doc comments to the declaration in the parser, we might be able to get quick documentation that way.

**Comment by Neppord** [comment]
@simonolander i thought the lexer already did so, its just that the parser treat comments as whitespace.

I have already played around a bit with this, should we talk?
