### ISSUE TITLE
When creating a new file outside of src or test it adds the whole path to system root instead of project root to module name

### ISSUE THREAD

**Issue by Neppord** [intellij-purescript/intellij-purescript#94]
How should we handle this?

I have two ideas:
 1. check if folder starts with Capital letter, and assume its a module
 2. remove the path of the project from the path to the directory before counting words
 
 what do you think @simonolander?

**Comment by simonolander** [comment]
The second alternative sounds more robust. I struggled a bit with not receiving proper project paths in the unit tests, so there might be some gotchas there. Or it will just work, we'll see!
